# Documentation: https://roots.io/trellis/docs/mail/
mail_smtp_server: smtp.mailgun.org:465
mail_admin: postmaster@2k17.fr
mail_hostname: smtp.mailgun.org
mail_user: postmaster@mg.2k17.fr
mail_password: "{{ vault_mail_password }}" # Define this variable in group_vars/all/vault.yml
